name: PHP Composer

on:
  push:
    tags:        
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Publish to Composer packages
      id: composer-publish
      uses: mnavarrocarter/packagist-update@v1.0.0
      with:
        username: "panxl6"
        api_token: ${{ secrets.packagist_token }}
        package_name: panxl6/hello-php # No need to be explicit if you have checked out a composer.json
        domain: "packagist.org" # This is by default, so no need to specify this.
